#!/usr/bin/env python3
import sys


def solve(p: str, q: str):
    if (q < p):
        p, q = q, p
    alpha_to_index = {
        "A": 0,
        "B": 1,
        "C": 2,
        "D": 3,
        "E": 4,
        "F": 5,
        "G": 6
    }
    distance_list = [3, 1, 4, 1, 5, 9]
    p_index = alpha_to_index[p]
    q_index = alpha_to_index[q]
    ans = 0
    
    for i in range(p_index, q_index):
        ans += distance_list[i]
    print(ans)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    p = next(tokens)  # type: str
    q = next(tokens)  # type: str
    solve(p, q)

if __name__ == '__main__':
    main()
