#!/usr/bin/env python3
import sys

YES = "YES"  # type: str
NO = "NO"  # type: str


def solve(S: str):
    cans = ["dream", "dreamer", "erase", "eraser"]

    stack = [""]
    while stack:
        now_string = stack.pop()
        for can in cans:
            new_string = now_string + can
            if S[:len(new_string)] == new_string:
                if S == new_string:
                    print(YES)
                    return 
                stack.append(new_string)
    print(NO)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
