#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W = map(int, input().split())
    grid = []
    min_j = W
    max_j = 0
    min_i = H
    max_i = 0

    for i in range(H):
        row = input()
        for j, item in enumerate(row):
            if item == "#":
                min_i = min(min_i, i)
                max_i = max(max_i, i)
                min_j = min(min_j, j)
                max_j = max(max_j, j)
        grid.append(row)
    
    for i in range(min_i, max_i+1):
        for j in range(min_j, max_j+1):
            if grid[i][j] == ".":
                print(i+1, j+1)
                return
    # Failed to predict input format
    pass

if __name__ == '__main__':
    main()
