#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = map(int, input().split())
    a_set_list = []
    for _ in range(M):
        C_i = int(input())
        a_i_set = set(map(int, input().split()))
        a_set_list.append(a_i_set)
    
    ans = 0
    target_set = set(x for x in range(1, N+1))
    for i in range(2**M):
        total_set = set()
        for j in range(M):
            if (i >> j & 1):
                total_set = total_set | a_set_list[j]
        if total_set >= target_set:
            ans += 1
    print(ans)



    # Failed to predict input format
    pass

if __name__ == '__main__':
    main()
